# Generated by Django 6.0.4 on 2026-04-26 16:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FmPlayerPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=255, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'fm_player_position',
                'verbose_name_plural': 'fm_players_positions',
                'db_table': 'fm_player_position',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FmPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('photo', models.ImageField(blank=True, max_length=10, null=True, upload_to='', verbose_name='Photo')),
                ('national', models.CharField(blank=True, max_length=25, null=True, verbose_name='National')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('is_injury', models.BooleanField(default=False)),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Height')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Weight')),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='users.fmauthuser', verbose_name='Auth User')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='players.fmplayerposition', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'fm_player',
                'verbose_name_plural': 'fm_players',
                'db_table': 'fm_player',
                'ordering': ['-created_at'],
            },
        ),
    ]
