# Generated by Django 6.0.4 on 2026-04-26 16:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FmSystemRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'fm_system_role',
                'verbose_name_plural': 'fm_system_roles',
                'db_table': 'fm_system_role',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FmAuthUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=255, verbose_name='Username')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('password', models.TextField(verbose_name='Password')),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fm_auth_users', to='users.fmsystemrole', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'fm_auth_user',
                'verbose_name_plural': 'fm_auth_users',
                'db_table': 'fm_auth_user',
                'ordering': ['-created_at'],
            },
        ),
    ]
