# Generated by Django 6.0.4 on 2026-04-26 16:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FmStadium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Stadium name')),
                ('address', models.CharField(max_length=255, verbose_name='Stadium address')),
                ('quality', models.IntegerField(verbose_name='Quality')),
            ],
            options={
                'verbose_name': 'fm_stadium',
                'verbose_name_plural': 'fm_stadiums',
                'db_table': 'fm_stadium',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FmCoach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='Phone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
                ('level', models.CharField(blank=True, max_length=20, null=True, verbose_name='Level')),
                ('experience_years', models.IntegerField(blank=True, null=True, verbose_name='Experience Years')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fm_coaches', to='users.fmauthuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'fm_coach',
                'verbose_name_plural': 'fm_coaches',
                'db_table': 'fm_coach',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FmTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Team name')),
                ('headquarter', models.CharField(max_length=255, verbose_name='Team headquarter')),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.fmcoach', verbose_name='Coach')),
                ('stadium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.fmstadium', verbose_name='Stadium')),
            ],
            options={
                'verbose_name': 'fm_team',
                'verbose_name_plural': 'fm_teams',
                'db_table': 'fm_team',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FmPlayerTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('584bfae9-ed45-429e-bf79-78b4edeb7374'), editable=False, primary_key=True, serialize=False)),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Left team')),
                ('joined_at', models.DateTimeField(verbose_name='Join team')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fm_player_team', to='players.fmplayer', verbose_name='Player')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fm_player_team', to='teams.fmteam', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'fm_player_teams',
                'verbose_name_plural': 'fm_player_teams',
                'db_table': 'fm_player_team',
                'ordering': ['-id'],
            },
        ),
    ]
