# Generated by Django 6.0.4 on 2026-04-26 16:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FmMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='Home score')),
                ('away_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='Away score')),
                ('match_date', models.DateTimeField(verbose_name='Match date')),
                ('away_team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='teams.fmteam', verbose_name='Away team')),
                ('home_team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='teams.fmteam', verbose_name='Home team')),
                ('stadium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fm_matches', to='teams.fmstadium', verbose_name='Stadium')),
            ],
            options={
                'verbose_name': 'fm_match',
                'verbose_name_plural': 'fm_matches',
                'db_table': 'fm_match',
                'ordering': ['-created_at'],
            },
        ),
    ]
